name: Umar Mughal
favicon: null
layout_spectrum: 0.7234042
typography_spectrum: 0.5297872
title: 'UI Designer & Frontend Developer'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424243'
    - '#fec800'
    - '#ffffff'
    - '#acacac'
    - '#7f660c'
  brandStrength: 0.1875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
